### ISSUE TITLE
PHP exception from Passwords app during Nextcloud background job (cron)

### ISSUE THREAD

**Issue by dboehmer** [nextcloud/password_policy#628]
Yesterday I updated Nextcloud from 26 to 29 and all apps are up to date now. Since yesterday my hourly cronjob fails with the same error message all the time.

### Steps to reproduce
1. Long existing Nextcloud instance
2. Web updater + occ Upgrades to version 29
3. long existing cronjob that runs the PHP script as a system process

### Expected behaviour
Background job should run successfully and silently.

### Actual behaviour
Cronjob fails after ~1 second with this output:

```
ArgumentCountError: Too few arguments to function OCA\Passwords\Cron\SynchronizeShares::__construct(), 0 passed in .../nextcloud/lib/private/BackgroundJob/JobList.php on line 330 and exactly 9 expected in .../nextcloud/apps/passwords/lib/Cron/SynchronizeShares.php:58
Stack trace:
#0 .../nextcloud/lib/private/BackgroundJob/JobList.php(330): OCA\Passwords\Cron\SynchronizeShares->__construct()
#1 .../nextcloud/lib/private/BackgroundJob/JobList.php(235): OC\BackgroundJob\JobList->buildJob()
#2 .../nextcloud/cron.php(163): OC\BackgroundJob\JobList->getNext()
#3 {main}
```

### Server configuration

**Operating system**: Gentoo Linux

**Web server:** Apache

**Database:** some MariaDB

**PHP version:** 8.2

**Nextcloud version:** 29.0.4 (see Nextcloud admin page)

**Where did you install Nextcloud from:** Tarball extracted in shared web space

**List of activated apps:** CLI access is cumbersome. Default apps + Passwords 2024.7.20, Nextcloud Office, Group folders, Teams.

<!--
```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```-->

**Nextcloud configuration:**

```php
<?php
$CONFIG = array (
  'instanceid' => '***',
  'passwordsalt' => '***',
  'secret' => '***',
  'trusted_domains' => 
  array (
    0 => 'cloud.***',
  ),
  'datadirectory' => '***/nextcloud/data',
  'dbtype' => 'mysql',
  'version' => '29.0.4.1',
  'integrity.check.disabled' => true,
  'default_language' => 'de',
  'default_locale' => 'de',
  'trashbin_retention_obligation' => 'auto, 30',
  'version_retention_obligation' => 'auto, 30',
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'log_type' => 'file',
  'logfile' => '/dev/null',
  'overwrite.cli.url' => 'https://cloud.***',
  'htaccess.RewriteBase' => '/',
  'dbname' => '***',
  'dbhost' => '***',
  'dbport' => '',
  'dbtableprefix' => 'nextcloud_',
  'mysql.utf8mb4' => true,
  'dbuser' => '***',
  'dbpassword' => '***',
  'installed' => true,
  'mail_from_address' => 'nextcloud',
  'mail_smtpmode' => 'smtp',
  'mail_sendmailmode' => 'smtp',
  'mail_domain' => '***',
  'debug' => false,
  'mail_smtpdebug' => true,
  'theme' => '',
  'loglevel' => 0,
  'skeletondirectory' => '',
  'updater.release.channel' => 'stable',
  'maintenance' => false,
  'maintenance_window_start' => 1,
  'default_phone_region' => 'DE',
  'mail_smtphost' => 'mail.***',
  'mail_smtpport' => '465',
  'mail_smtpsecure' => 'ssl',
  'mail_smtpauth' => 1,
  'mail_smtpauthtype' => 'LOGIN',
  'mail_smtpname' => 'nextcloud@***',
  'mail_smtppassword' => '***',
);
```

### Client configuration
**Browser:** — no browser involved

**Operating system:** —

#### Nextcloud log (data/owncloud.log)

Nothing written to PHP error log

#### Browser log
—

**Comment by susnux** [comment]
This is the `password_policy` app, I think you want to report this here instead: https://github.com/marius-wieschollek/passwords/issues
